<?php
/*
 * Copyright (C) 2020  Paul W. Lane <kc9eye@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
require_once(dirname(__DIR__).'/lib/init.php');
$server->userMustHaveRole('Materials');
$cell = new WorkCell($server->pdo,$_REQUEST['cellid']);
echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "<head>\n";
echo "<title>{$cell->Name}</title>\n";
echo "<link rel='stylesheet' type='text/css' href='{$server->config['application-root']}/wwwroot/css/print.css' />\n";
echo "<style>\n";
echo "media print {
    tr {
        page-break-inside: avoid;
    }
}";
echo "table {
        width:100%;
    }
    table, td, th {
        border-collapse: collapse;
        border: 1px solid black;
    }
    th,td {
        text-align:center;
    }
    td {
        height:30px;
        vertical-align: center;
    }
    #notes {
        width:35%;
    }\n";
echo "</style>\n";
echo "</head>\n";
echo "<body>\n";
echo "<h1>{$cell->Product} / {$cell->Name}</h1>\n";
echo "<p>Generated by: {$server->security->user['firstname']} {$server->security->user['lastname']} at: ".date('c')."</p>\n";
echo "<hr />\n";
echo "<table>";
echo "<tr><th>Number</th><th>Quantity</th><th>Description</th></tr>";
foreach($cell->Material as $row) {
    echo "<tr><td>";
    echo "<img src='{$server->config['application-root']}/data/barcode?barcode={$row['number']}&&width=200&height=50&format=png&text=0' alt='[BARCODE]' />";
    echo "<br />";
    echo "<span class='text-center'>{$row['number']}</span>";
    echo "</td>";
    echo "<td>{$row['qty']}</td>";
    echo "<td>{$row['description']}</td></tr>";
}
echo "</table>";
echo "</body>\n";
echo "</html>\n";