<?php
/* This file is part of UData.
 * Copyright (C) 2018 Paul W. Lane <kc9eye@outlook.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
require_once(dirname(__DIR__).'/lib/init.php');

$server->userMustHavePermission('maintenanceAccess');

if (empty($_REQUEST['cellid'])) {
    $server->newEndUserDialog('No cell ID given, unable to handle request.',DIALOG_FAILURE,$server->config['application-root'].'/');
}

$cell = new WorkCell($server->pdo,$_REQUEST['cellid']);
echo "<!DOCTYPE html>";
echo "<html>";
echo "<head>";
echo "<title>{$cell->Name} Pick List</title>";
echo "<link rel='stylesheet' type='text/css' href='{$server->config['application-root']}/wwwroot/css/print.css' />";
echo "<style>";
echo "table {
        width:100%;
    }
    table, td, th {
        border-collapse: collapse;
        border: 1px solid black;
    }
    th {
        text-align:center;
    }
    td {
        height:30px;
        vertical-align: center;
        text-align:left;
    }";
echo "</style>";
echo "<head>";
echo "<body>";
echo "<h1>Tool Pick List for: {$cell->Name}</h1>";
echo "<p>Generated by: {$server->security->user['firstname']} {$server->security->user['lastname']} at: ".date('c')."</p>";
echo "<hr />";
echo "<table style='line-height:1.5'>";
echo "<tr><th>Picked</th><th>Qty.</th><th>Category</th><th>Tool</th><th>Torque Value</th><th>Torque Units</th><th>Torque Label</th></tr>";
foreach($cell->Tools as $tool) {
    echo "<tr><td><input type='checkbox' />";
    echo "</td><td>{$tool['qty']}</td><td>{$tool['category']}</td><td>{$tool['description']}</td>";
    echo "<td>{$tool['torque_val']}</td><td>{$tool['torque_units']}</td><td>{$tool['torque_label']}</td></tr>";
}
echo "<tr><td style='height:300px;text-align:left;vertical-align:top;' colspan='7'>Amendments and Annotations:</td></tr>";
echo "</table>";
echo "<script>window.print()</script>";
echo "</body>";
echo "</html>";

